version: '3.8'

services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_gif_app
    environment:
      - DATABASE_URL=postgresql://viasapientium:Dragon@1@db:5432/gifdatabase
    ports:
      - "8080:8080"
    depends_on:
      - db


  db:
    image: postgres:14
    container_name: gifdatabase
    environment:
      POSTGRES_USER: viasapientium
      POSTGRES_PASSWORD: Dragon@1
      POSTGRES_DB: gifdatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
