services:
  frontend-dev:
    build:
      context: ./frontend
      target: development
    environment:
      - VITE_API_URL_DEV=${API_DEV}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    environment:
      - DATABASE_URL=postgresql://${PG_USER_DEV}:${PG_PASSWORD_DEV}@db:${PG_PORT_DEV}/${PG_DBNAME}
      - RUST_LOG_DEV=${RUST_LOG_DEV}
      - LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu/
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${PG_USER_DEV}
      - POSTGRES_PASSWORD=${PG_PASSWORD_DEV}
      - POSTGRES_DB=${PG_DBNAME}
    ports:
      - "${PG_PORT_DEV}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
