[package]
name = "rust-to-gif"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = "7.1.0"
image = "0.25.2"
gif = "0.13.1"
actix-web = { version = "4.0", features = ["macros"] }
deadpool-postgres = "0.14"
log = "0.4"
env_logger = { version = "0.11.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde", "std"] }
tokio-postgres = "0.7"
tokio-postgres-migration = "0.1.0"
argon2 = "0.5.2"
rand = "0.8.4"
uuid = { version = "1.1", features = ["v4"] }

[[bin]]
name = "rust-to-gif"
path = "src/main.rs"

[features]
default = []
