unstable_features = true
blank_lines_upper_bound = 1

max_width = 100
hard_tabs = false
tab_spaces = 2


format_code_in_doc_comments = true
use_small_heuristics = "Off"

newline_style = "Unix"
reorder_imports = true


match_block_trailing_comma = true
struct_field_align_threshold = 20
